## Matrik
### Definisi Matrik
Matrik adalah susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang. Matrik disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Ukuran matrik ditentukan oleh jumlah baris dan kolom yang dikandungnya.

Matrik diberi nama dengan huruf kapital dan anggotannya dinyatakan dengan huruf kecil. Banyaknya baris dan kolom suatu matriks disebut ordo. Berikut adalah beberapa contoh matrik.

1. Matrik 4 x 4

$$
\begin{split}
A = \left[ \begin{array}{rrrr}
1 & 8 & 9 & 4 \\
2 & 7 & -1 & -3 \\
2 & 6 & 2 & 5 \\
4 & 5 & 3 & -2  \\
\end{array}\right]
\end{split}
$$

2. Matrik 3 x 2

$$
\begin{split}
B = \left[ \begin{array}{rrrr}
3 & 9 \\
5 & 3 \\
7 & 1 \\
\end{array}\right]
\end{split}
$$

3. Matrik 2 x 2

$$
\begin{split}
C = \left[ \begin{array}{rrrr}
-1 & 9 \\
3 & 5 \\
\end{array}\right]
\end{split}
$$

4. Matrik 2 x 3

$$
\begin{split}
D = \left[ \begin{array}{rrrr}
-2 & 8 & 3 \\
-3 & 9 & 7 \\
\end{array}\right]
\end{split}
$$

### Operasi Artimatika Matrik
Operasi aritmatika matrik adalah serangkaian operasi matematika yang dilakukan pada matrik meliputi penjumlahan, pengurangan, perkalian, perkalian dengan skalar.

### Penjumlahan
Penjumlahan matrik adalah operasi antara dua matrik yang memiliki dimensi yang sama yaitu jumlah baris dan kolomnya harus sama. Operasi penjumlahan dilakukan dengan menjumlahkan elemen-elemen yang sesuai dari kedua matrik.

### Konsep Penjumlahan Matrik


In [ ]:
import numpy as np
a = np.array(([2,3],[9,1]))
b = np.array(([5,7],[8,2]))

c = np.add (a,b)
print(a)
print()
print(b)
print()
print("hasil : ")
print(c)

[[2 3]
 [9 1]]

[[5 7]
 [8 2]]

hasil : 
[[ 7 10]
 [17  3]]


### Perkalian Matrik
Perkalian matrik adalah nilai pada matrik yang bisa dihasilkan dengan cara dikalikan-nya tiap baris degan kolom yang memiliki jumlah baris yang sama. Operasi ini melibatkan perkalian elemen-elemen matrik. Untuk melakukan perkalian matrik A dan B, jumlah kolom dalam matrik A harus sama dengan jumlah baris dalam matrik B.

### Konsep Perkalian Matrik

In [ ]:
import numpy as np
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
b = np.array(([9,8,7],[6,5,4],[3,2,1]))

c = np.matmul(a,b)
print(a)
print()
print(b)
print()
print("hasil : ")
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

hasil : 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
