## Matrik
### Definisi Matrik
Matrik adalah susunan bilangan real atau bilangan kompleks (atau elemen-elemen) yang disusun dalam baris dan kolom sehingga membentuk jajaran persegi panjang. Matrik disusun berdasarkan baris dan kolom, serta ditempatkan di dalam tanda kurung. Ukuran matrik ditentukan oleh jumlah baris dan kolom yang dikandungnya.

Matrik diberi nama dengan huruf kapital dan anggotannya dinyatakan dengan huruf kecil. Banyaknya baris dan kolom suatu matriks disebut ordo. Berikut adalah beberapa contoh matrik.

1. Matrik 4 x4

$$
\begin{split}
A = \left[ \begin{array}{rrrr}
1 & 8 & 9 & 4 \\
2 & 7 & -1 & -3 \\
2 & 6 & 2 & 5 \\
4 & 5 & 3 & -2  \\
\end{array}\right]
\end{split}
$$

2. Matrik 3 x 2

$$
\begin{split}
B = \left[ \begin{array}{rrrr}
3 & 9 \\
5 & 3 \\
7 & 1 \\
\end{array}\right]
\end{split}
$$

3. Matrik 2 x 2

$$
\begin{split}
C = \left[ \begin{array}{rrrr}
-1 & 9 \\
3 & 5 \\
\end{array}\right]
\end{split}
$$

4. Matrik 2 x 3

$$
\begin{split}
D = \left[ \begin{array}{rrrr}
-2 & 8 & 3 \\
-3 & 9 & 7 \\
\end{array}\right]
\end{split}
$$

### Operasi Artimatika Matrik
Operasi aritmatika matrik adalah serangkaian operasi matematika yang dilakukan pada matrik meliputi penjumlahan, pengurangan, perkalian, perkalian dengan skalar.

### Penjumlahan
Penjumlahan matrik adalah operasi antara dua matrik yang memiliki dimensi yang sama yaitu jumlah baris dan kolomnya harus sama. Operasi penjumlahan dilakukan dengan menjumlahkan elemen-elemen yang sesuai dari kedua matrik.

### Konsep Penjumlahan Matrik
Berikut contoh penjumlahan matrik.


In [ ]:
import numpy as np
a = np.array(([2,3],[9,1]))
b = np.array(([5,7],[8,2]))

c = np.add (a,b)
print(a)
print()
print(b)
print()
print("hasil : ")
print(c)

[[2 3]
 [9 1]]

[[5 7]
 [8 2]]

hasil : 
[[ 7 10]
 [17  3]]


### Perkalian Matrik
Perkalian matrik adalah nilai pada matrik yang bisa dihasilkan dengan cara dikalikan-nya tiap baris degan kolom yang memiliki jumlah baris yang sama. Operasi ini melibatkan perkalian elemen-elemen matrik. Untuk melakukan perkalian matrik A dan B, jumlah kolom dalam matrik A harus sama dengan jumlah baris dalam matrik B.

### Konsep Perkalian Matrik
Berikut contoh perkalian matrik.

In [ ]:
import numpy as np
a = np.array(([1,2,3],[4,5,6],[7,8,9]))
b = np.array(([9,8,7],[6,5,4],[3,2,1]))

c = np.matmul(a,b)
print(a)
print()
print(b)
print()
print("hasil : ")
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]

hasil : 
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


## Penyelesaian persamaan menggunakan invers matrik

Kita diberikan sistem persamaan linear:

$
\begin{aligned}
    -7x_1 - 6x_2 - 12x_3 &= -33 \\
    5x_1 + 5x_2 + 7x_3 &= 24 \\
    x_1 + 4x_3 &= 5
\end{aligned}
$

#### **1. Bentuk Matriks**
Sistem persamaan di atas dapat dituliskan dalam bentuk matriks:

$
A \mathbf{x} = \mathbf{b}
$

dengan:

$
A =
\begin{bmatrix}
-7 & -6 & -12 \\
5 & 5 & 7 \\
1 & 0 & 4
\end{bmatrix},
\quad
\mathbf{x} =
\begin{bmatrix}
x_1 \\ x_2 \\ x_3
\end{bmatrix},
\quad
\mathbf{b} =
\begin{bmatrix}
-33 \\ 24 \\ 5
\end{bmatrix}
$

Penyelesaian sistem menggunakan invers matriks diberikan oleh:

$
\mathbf{x} = A^{-1} \mathbf{b}
$

Kita akan mencari $ A^{-1} $ menggunakan operasi baris elementer.

---

#### **2. Menentukan $ A^{-1} $ Menggunakan Operasi Baris Elementer**
Kita mulai dengan matriks augmented:

$
\left[ A \,|\, I \right] =
\left[
\begin{array}{ccc|ccc}
-7 & -6 & -12 & 1 & 0 & 0 \\
5 & 5 & 7 & 0 & 1 & 0 \\
1 & 0 & 4 & 0 & 0 & 1
\end{array}
\right]
$

**Langkah 1: Ubah elemen (1,1) menjadi 1**
Kita bagi baris pertama dengan $ -7 $:

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
5 & 5 & 7 & 0 & 1 & 0 \\
1 & 0 & 4 & 0 & 0 & 1
\end{array}
\right]
$

**Langkah 2: Nulifikasi elemen (2,1) dan (3,1)**  
Baris kedua: $ R_2 \leftarrow R_2 - 5R_1 $  
Baris ketiga: $ R_3 \leftarrow R_3 - R_1 $

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
0 & \frac{5}{7} & \frac{1}{7} & \frac{5}{7} & 1 & 0 \\
0 & -\frac{6}{7} & \frac{16}{7} & \frac{1}{7} & 0 & 1
\end{array}
\right]
$

**Langkah 3: Ubah elemen (2,2) menjadi 1**  
Kita kalikan baris kedua dengan $ \frac{7}{5} $:

$
\left[
\begin{array}{ccc|ccc}
1 & \frac{6}{7} & \frac{12}{7} & -\frac{1}{7} & 0 & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & -\frac{6}{7} & \frac{16}{7} & \frac{1}{7} & 0 & 1
\end{array}
\right]
$

**Langkah 4: Nulifikasi elemen (1,2) dan (3,2)**  
Baris pertama: $ R_1 \leftarrow R_1 - \frac{6}{7} R_2 $  
Baris ketiga: $ R_3 \leftarrow R_3 + \frac{6}{7} R_2 $

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & \frac{10}{7} & -\frac{5}{21} & -\frac{6}{5} & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & \frac{22}{7} & \frac{11}{35} & \frac{42}{35} & 1
\end{array}
\right]
$

**Langkah 5: Ubah elemen (3,3) menjadi 1**  
Kita kalikan baris ketiga dengan $ \frac{7}{22} $:

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & \frac{10}{7} & -\frac{5}{21} & -\frac{6}{5} & 0 \\
0 & 1 & \frac{1}{5} & \frac{1}{5} & \frac{7}{5} & 0 \\
0 & 0 & 1 & \frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{array}
\right]
$

**Langkah 6: Nulifikasi elemen (1,3) dan (2,3)**  
Baris pertama: $ R_1 \leftarrow R_1 - \frac{10}{7} R_3 $  
Baris kedua: $ R_2 \leftarrow R_2 - \frac{1}{5} R_3 $

$
\left[
\begin{array}{ccc|ccc}
1 & 0 & 0 & -\frac{8}{21} & -\frac{9}{5} & -\frac{10}{22} \\
0 & 1 & 0 & \frac{1}{5} - \frac{1}{50} & \frac{7}{5} - \frac{21}{110} & -\frac{7}{110} \\
0 & 0 & 1 & \frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{array}
\right]
$

Setelah disederhanakan, kita dapatkan invers matriks $ A^{-1} $:

$
A^{-1} =
\begin{bmatrix}
-\frac{8}{21} & -\frac{9}{5} & -\frac{5}{11} \\
\frac{2}{7} & \frac{37}{35} & -\frac{7}{55} \\
\frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{bmatrix}
$

---

#### **3. Menghitung $ \mathbf{x} = A^{-1} \mathbf{b} $**

$
\mathbf{x} =
\begin{bmatrix}
-\frac{8}{21} & -\frac{9}{5} & -\frac{5}{11} \\
\frac{2}{7} & \frac{37}{35} & -\frac{7}{55} \\
\frac{1}{10} & \frac{21}{22} & \frac{7}{22}
\end{bmatrix}
\begin{bmatrix}
-33 \\ 24 \\ 5
\end{bmatrix}
$

Setelah dihitung, diperoleh:

$
\mathbf{x} =
\begin{bmatrix}
1 \\ 2 \\ 1
\end{bmatrix}
$

Jadi, solusi dari sistem persamaan adalah:

$
x_1 = 1, \quad x_2 = 2, \quad x_3 = 1
$