# Apa itu SVD (Singular Value Decompotion)

SVD (Singular Value Decompotion) adalah metode dalam aljabar linear yang digunakan untuk memfaktorkan (memecah) sebuah matriks menjadi tiga matriks khusus. SVD sangat berguna dalam analisis data, kompresi informasi, dan pembelajaran mesin.

Jika diberikan sebuah matriks A berukuran $m \times n$, maka SVD (Singular Value Decomposition) menyatakan bahwa:

$$
A = U \Sigma V^T
$$

di mana:
- $A$ adalah matriks asli berukuran $m \times n$
- $U$ adalah matriks ortogonal berukuran $m \times m$
- $\Sigma$ adalah matriks diagonal berukuran $m \times n$ yang berisi singular values
- $V^T$ adalah transpose dari matriks ortogonal $V$ berukuran $n \times n$

## Kegunaan SVD (Singular Value Decompotion)

1. **Pengurangan Dimensi (Dimensionality Reduction) :**
SVD membantu mengurangi dimensi data sambil mempertahankan informasi yang paling penting. Ini sangat berguna dalam pembelajaran mesin dan analisis data untuk memproses data berdimensi tinggi.
2. **Analisis Data :**
SVD dapat digunakan untuk mengidentifikasi pola dan struktur tersembunyi dalam data. Analisis Komponen Utama (PCA) adalah contoh aplikasi SVD dalam analisis data, di mana SVD membantu dalam mereduksi dimensi data dan mengekstrak informasi penting.
3. **Kompresi Data :**
SVD dapat digunakan untuk mengompresi data, terutama data gambar dan video, dengan mempertahankan informasi yang paling signifikan dan membuang informasi yang kurang penting.
4. **Sistem Rekomendasi :**
SVD dapat digunakan untuk membangun sistem rekomendasi dengan memprediksi preferensi pengguna berdasarkan riwayat interaksi mereka.
5. **Pemrosesan Citra :**
SVD digunakan dalam berbagai tugas pemrosesan citra, seperti kompresi gambar, pemulihan citra yang terdegradasi, dan deteksi objek.
6. **Analisis Semantik Laten (Latent Semantic Analysis / LSA) :**
SVD dapat digunakan untuk analisis teks, seperti dalam penambangan teks untuk menemukan hubungan tersembunyi antara kata-kata dan dokumen.
7. **Penghilangan Noise pada Gambar :**
SVD dapat digunakan untuk menghilangkan noise dari gambar dengan membuang komponen-komponen yang kurang penting yang mungkin mewakili noise.





## Bagaimana Formula SVD (Singular Value Decompotion)

Bagaimana Formula SVD (Singular Value Decomposition)}\

Jika:
$$
A_{m \times n} = U_{m \times m} \cdot \Sigma_{m \times n} \cdot V^T_{n \times n}
$$

Maka:

$\mathbf{U}$: Kolom-kolomnya adalah \textbf{left singular vectors}, yaitu vektor eigen dari matriks $A A^T$.
  
$\mathbf{\Sigma}$: Matriks diagonal yang berisi \textbf{singular values}, yaitu akar dari nilai eigen dari $A^T A$ atau $A A^T$.
  
$\mathbf{V}$: Kolom-kolomnya adalah \textbf{right singular vectors}, yaitu vektor eigen dari matriks $A^T A$.




## Matriks 2x2

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
$$

---

##  *Langkah 1: Hitung $A^T A$ dan $A A^T$*

Karena $A$ adalah matriks simetris $2 \times 2$, maka $A^T = A$.

$$
A^T A = A A =
\begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
\begin{bmatrix}
3 & 1 \\
1 & 3 \\
\end{bmatrix}
=
\begin{bmatrix}
3×3 + 1×1 & 3×1 + 1×3 \\
1×3 + 3×1 & 1×1 + 3×3 \\
\end{bmatrix}
=
\begin{bmatrix}
9 + 1 & 3 + 3 \\
3 + 3 & 1 + 9 \\
\end{bmatrix}
=
\begin{bmatrix}
10 & 6 \\
6 & 10 \\
\end{bmatrix}
$$

---

##  *Langkah 2: Cari Eigenvalue dari $A^T A$*

Misal $\lambda$ adalah eigenvalue, maka:

$$
\det(A^TA - \lambda I) = 0
$$

$$
\begin{vmatrix}
10 - \lambda & 6 \\
6 & 10 - \lambda \\
\end{vmatrix} = 0
$$

$$
(10 - \lambda)^2 - 36 = 0
\Rightarrow (10 - \lambda)^2 = 36
\Rightarrow 10 - \lambda = \pm 6
$$

$$
\lambda_1 = 4,\quad \lambda_2 = 16
$$

---

##  *Langkah 3: Hitung Singular Values*

$$
\sigma_i = \sqrt{\lambda_i}
\Rightarrow
\sigma_1 = \sqrt{16} = 4,\quad \sigma_2 = \sqrt{4} = 2
$$

---

## *Langkah 4: Cari V (eigenvector dari $A^TA$)*

Gunakan $A^TA = \begin{bmatrix} 10 & 6 \\ 6 & 10 \end{bmatrix}$

### Untuk $\lambda = 16$:

$$
(A^TA - 16I) v = 0
\Rightarrow
\begin{bmatrix}
-6 & 6 \\
6 & -6 \\
\end{bmatrix}
\Rightarrow
v_1 = \begin{bmatrix}
1 \\
1 \\
\end{bmatrix} \quad \text{(sebelum normalisasi)}
$$

Normalisasi:

$$
v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

### Untuk $\lambda = 4$:

$$
(A^TA - 4I) v = 0
\Rightarrow
\begin{bmatrix}
6 & 6 \\
6 & 6 \\
\end{bmatrix}
\Rightarrow
v_2 = \begin{bmatrix}
1 \\
-1 \\
\end{bmatrix}
\Rightarrow
v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$

---

##  *Langkah 5: Bentuk $\Sigma$ dan $V$*

$$
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2 \\
\end{bmatrix}, \quad
V = \left[
\frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix},
\frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
\right]
=
\frac{1}{\sqrt{2}}
\begin{bmatrix}
1 & 1 \\
1 & -1 \\
\end{bmatrix}
$$

---

##  *Langkah 6: Hitung $U$* dengan rumus:

$$
U_i = \frac{1}{\sigma_i} A v_i
$$

### Untuk $\sigma_1 = 4$, $v_1 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}$

$$
u_1 = \frac{1}{4} A v_1 = \frac{1}{4} A \cdot \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
= \frac{1}{4\sqrt{2}} \begin{bmatrix} 3+1 \\ 1+3 \end{bmatrix}
= \frac{1}{4\sqrt{2}} \begin{bmatrix} 4 \\ 4 \end{bmatrix}
= \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

### Untuk $\sigma_2 = 2$, $v_2 = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}$

$$
u_2 = \frac{1}{2} A v_2 = \frac{1}{2\sqrt{2}} \begin{bmatrix} 3 - 1 \\ 1 - 3 \end{bmatrix}
= \frac{1}{2\sqrt{2}} \begin{bmatrix} 2 \\ -2 \end{bmatrix}
= \frac{1}{\sqrt{2}} \begin{bmatrix} 1 \\ -1 \end{bmatrix}
$$

---

## Hasil Akhir SVD

$$
U =  \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
\end{bmatrix},\quad
\Sigma = \begin{bmatrix}
4 & 0 \\
0 & 2 \\
\end{bmatrix},\quad
V^T = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \\
\end{bmatrix}^T
$$


In [1]:
import numpy as np

# Matriks asli
A = np.array([
    [3, 1],
    [1, 3]
])

# SVD dengan NumPy
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nV^T:")
print(VT)

# Bentuk S ke dalam bentuk matriks diagonal (Sigma)
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

print("\nSigma:")
print(Sigma)

# Perkalian kembali: U @ Sigma @ V^T
A_reconstructed = U @ Sigma @ VT

print("\nRekonstruksi A dari UΣV^T:")
print(A_reconstructed)

# Cek apakah hasilnya sama
print("\nApakah A sama dengan rekonstruksi? ", np.allclose(A, A_reconstructed))


Matrix A:
[[3 1]
 [1 3]]

U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular values (S):
[4. 2.]

V^T:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Sigma:
[[4. 0.]
 [0. 2.]]

Rekonstruksi A dari UΣV^T:
[[3. 1.]
 [1. 3.]]

Apakah A sama dengan rekonstruksi?  True


## Matriks 4x2

Langkah-langkah Dekomposisi SVD

Dekomposisi Singular Value (SVD) dari sebuah matriks $A$ dinyatakan sebagai:
$$
A = U \Sigma V^T
$$

Langkah 1: Matriks A
Misalkan diberikan matriks:
$$
A =
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1
\end{bmatrix}
\quad \text{(ukuran } 4 \times 2)
$$

Langkah 2: Hitung $A^T A$
$$
A^T A =
\begin{bmatrix}
3 & 2 & 4 & 1 \\
7 & 5 & 3 & 1
\end{bmatrix}
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1
\end{bmatrix}
=
\begin{bmatrix}
30 & 44 \\
44 & 84
\end{bmatrix}
$$

Langkah 3: Cari Nilai Eigen dari $A^T A$
Tentukan akar dari karakteristik determinan:
$$
\det(A^T A - \lambda I) = 0
$$
$$
\det \begin{bmatrix}
30 - \lambda & 44 \\
44 & 84 - \lambda
\end{bmatrix} = 0
$$
$$
(30 - \lambda)(84 - \lambda) - 44^2 = 0
$$
$$
\lambda^2 - 114\lambda + 584 = 0
$$
$$
\lambda = \frac{114 \pm \sqrt{114^2 - 4 \cdot 1 \cdot 584}}{2} = \frac{114 \pm \sqrt{10660}}{2}
$$
$$
\Rightarrow \lambda_1 \approx 108.63,\quad \lambda_2 \approx 5.37
$$

Langkah 4: Nilai Singular
$$
\sigma_1 = \sqrt{108.63} \approx 10.42,\quad \sigma_2 = \sqrt{5.37} \approx 2.32
$$

Langkah 5: Matriks $\Sigma$
Karena $A$ berukuran $4 \times 2$, maka matriks $\Sigma$ berbentuk:
$$
\Sigma =
\begin{bmatrix}
10.42 & 0 \\
0 & 2.32 \\
0 & 0 \\
0 & 0
\end{bmatrix}
\quad (4 \times 2)
$$

Langkah 6: Matriks $V$
Berdasarkan eigenvektor dari $A^T A$, diperoleh:
$$
V =
\begin{bmatrix}
-0.4884 & -0.8726 \\
-0.8726 & 0.4884
\end{bmatrix}
\quad \Rightarrow \quad
V^T =
\begin{bmatrix}
-0.4884 & -0.8726 \\
-0.8726 & 0.4884
\end{bmatrix}
$$

Langkah 7: Matriks $U$
Gunakan:
$$
u_i = \frac{1}{\sigma_i} A v_i
$$

Hasilnya setelah normalisasi adalah:
$$
U =
\begin{bmatrix}
-0.7267 & -0.3453 & 0.7732 & 0.0853 \\
-0.5124 & -0.3004 & -0.3118 & -0.7613 \\
-0.4386 & 0.8736 & -0.4639 & 0.2802 \\
-0.1306 & 0.1657 & -0.2996 & 0.5785
\end{bmatrix}
$$

Verifikasi
$$
A \approx U \Sigma V^T
=
\begin{bmatrix}
3 & 7 \\
2 & 5 \\
4 & 3 \\
1 & 1
\end{bmatrix}
\quad \text{(rekonstruksi mendekati A asli)}
$$




In [2]:
import numpy as np

# Matriks asli
A = np.array([
    [3, 7],
    [2, 5],
    [4, 3],
    [1, 1]
])

# SVD dengan NumPy
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nSingular values (S):")
print(S)
print("\nV^T:")
print(VT)

# Bentuk S ke dalam bentuk matriks diagonal (Sigma)
Sigma = np.zeros_like(A, dtype=float)
np.fill_diagonal(Sigma, S)

print("\nSigma:")
print(Sigma)

# Perkalian kembali: U @ Sigma @ V^T
A_reconstructed = U @ Sigma @ VT

print("\nRekonstruksi A dari UΣV^T:")
print(A_reconstructed)

# Cek apakah hasilnya sama
print("\nApakah A sama dengan rekonstruksi? ", np.allclose(A, A_reconstructed))


Matrix A:
[[3 7]
 [2 5]
 [4 3]
 [1 1]]

U:
[[-0.72667296 -0.34526321 -0.57386797 -0.15302052]
 [-0.51235825 -0.300381    0.79239419  0.13918232]
 [-0.4386146   0.87355405  0.0817107  -0.19453511]
 [-0.13058586  0.16573437 -0.19002726  0.95883737]]

Singular values (S):
[10.42226645  2.31869834]

V^T:
[[-0.48835631 -0.87264432]
 [ 0.87264432 -0.48835631]]

Sigma:
[[10.42226645  0.        ]
 [ 0.          2.31869834]
 [ 0.          0.        ]
 [ 0.          0.        ]]

Rekonstruksi A dari UΣV^T:
[[3. 7.]
 [2. 5.]
 [4. 3.]
 [1. 1.]]

Apakah A sama dengan rekonstruksi?  True
